### ISSUE TITLE
Login don't work with ssowat enableb

### ISSUE THREAD

**Issue by c-cesar** [YunoHost-Apps/pleroma_ynh#131]
**Describe the bug**
Pleroma reports "incorrect credentials" when trying to login with LDAP credentials if ssowat (the yunohost dashboard button on botton right corner) is enabled on `/etc/nginx/conf.d/domain.root.tld.conf` 

**Versions**
- Hardware: VPS
- YunoHost version: 3.8.4.9 (stable)
- I have access to my server: screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no

**To Reproduce**
*Steps to reproduce the behavior.*
- install pleroma
- try to login with admin account
**Expected behavior**
be able to login

**Logs**
```
2020/07/26 01:08:47 [error] 592#592: *131357 open() "/usr/share/nginx/html/ynhtheme/custom_portal.js" failed (2: No such file or directory), client: 187.0.187.208, server: [domain], request: "GET /ynhtheme/custom_portal.js HTTP/2.0", host: "[domain]", referrer: "[domain]/pleroma/admin/"
2020/07/26 01:08:47 [error] 592#592: *131357 open() "/usr/share/nginx/html/ynhtheme/custom_overlay.css" failed (2: No such file or directory), client: 187.0.187.208, server: [domain], request: "GET /ynhtheme/custom_overlay.css HTTP/2.0", host: "[domain]", referrer: "https://[domain]/pleroma/admin/"
```

**Comment by alligatortue** [comment]
Hello,

It's been a while since the bug has been opened, but as of YunoHost 4.0.8 I also experience this.

It's partially fixable by signing in the Pleroma instance in a new "private" window (as explained [here](https://forum.yunohost.org/t/unable-to-login-to-pleroma-error-is-always-invalid-credentials-error/11777/3)[1]).

Now if I'm already logged with the SSO and try to access the Instance, I have the `Invalid credentials` message displayed and can't log in no matter what. The overlay is active and I can switch to-and-fro the user panel, but nothing else.

[1] https://forum.yunohost.org/t/unable-to-login-to-pleroma-error-is-always-invalid-credentials-error/11777/3

In the README : I don't understand what `LDAP supported but HTTP auth not.` exactly means, but if this is related to the issue then ignore this message I guess. I'll try to provide some relevant Nginx logs if I manage to find something

Cheers

**Comment by yalh76** [comment]
We already know what is the issue, it should be solved with YunoHost 4.1 and the new permission system.

**Comment by alligatortue** [comment]
Good to know then, thanks for the feedback

**Comment by supermamie** [comment]
I just installed a Pleroma on a 4.1 YunoHost and I can not log in with the Pleroma interface (I need a private browsing tab to be able to do that).
It works with the Mastodon interface.

**Comment by yalh76** [comment]
> 
> 
> I just installed a Pleroma on a 4.1 YunoHost and I can not log in with the Pleroma interface (I need a private browsing tab to be able to do that).
> It works with the Mastodon interface.

Having YunoHost 4.1 is not enough, pleroma package has to be upgraded to the new permission system ^^

**Comment by alligatortue** [comment]
Hello,

I still have the same problem than supermamie, despite running YunoHost 4.1.5 and Pleroma 2.2.0~ynh1. I tried to debug it today but for now I'm at lose about why it doesn't work.

In Nginx logs, browsing the front page of the Pleroma instance while logged in the SSO displays the following events :

`tail -f /var/log/nginx/foo.bar.fr-error.log`
```
...
2021/01/15 19:57:56 [error] 28625#28625: *124096 connect() failed (111: Connection refused) while connecting to upstream, client: 204.12.243.122, server: foo.bar.fr, request: "POST /inbox HTTP/1.1", upstream: "http://[::1]:8095/inbox", host: "foo.bar.fr"
...
2021/01/15 20:00:28 [error] 28625#28625: *124166 connect() failed (111: Connection refused) while connecting to upstream, client: 138.37.89.234, server: foor.bar.fr, request: "GET / HTTP/1.1", upstream: "http://[::1]:8095/", host: "foo.bar.fr"
...
```
In the access log, this specific entry stands out since we can find it as well in the dev console of the web browser :

`tail -f /var/log/nginx/foo.bar.fr-access.log`

```
2001:861:3580:86f0:9759:4d96:6e34:8ac0 - gator [15/Jan/2021:20:08:18 +0000] "POST /oauth/token HTTP/2.0" 400 52 "https://foo.bar.fr/main/public" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```
In the browser :
```
Failed to load resource: the server responded with a status of 400 () /oauth/token:1
Failed to load resource: the server responded with a status of 403 () /api/v1/mutes/:1
errors.js:12 Uncaught (in promise)  errors.js:12 
```
I guess it's really the first line that matters, but I (wildly) suppose the oauth thing is just a consequence of the LDAP authentication failing beforehand. I didn't try any modification in the Nginx conf yet.

I may try a full reinstall of the Pleroma application to see if this is specific to my instance or a more general problem

**Comment by yalh76** [comment]
Having YunoHost 4.1.+ is not enough, pleroma package has to be upgraded to the new permission system ^^

**Comment by alligatortue** [comment]
Oh ok, I thought `2.2.0~ynh1` was already using the new permission system, I understand now

**Comment by Melon-Bread** [comment]
Is `2.2.2~ynh1` not using the new permissions system?  
Just wanna make sure my issue is not caused by something else.

**Comment by yalh76** [comment]
Yes pleroma `2.2.2~ynh1` use new permissions system but I haven't tested, so let me know if it was enough to solve the problem ...

**Comment by alligatortue** [comment]
I still get the same behavior with `2.2.2~ynh1`
